---
# Mysql database tasks

- block:
    - name: Setup mysql jdbc connector
      include_role:
        name: amtega.mysql_jdbc_connector
      loop: >-
        {{ wso2am_mysql_databases
           | selectattr("driver_version", "defined")
           | map(attribute="driver_version")
           | list
           | unique }}
      loop_control:
        loop_var: wso2am_database_connector_version
      vars:
        mysql_jdbc_connector_version: "{{ wso2am_database_connector_version }}"
        mysql_jdbc_connector_dir: >-
          {{ wso2am_dir }}/repository/components/lib

    - name: Populate mysql database
      mysql_db:
        name: "{{ wso2am_database_item.name }}"
        login_host: "{{ wso2am_database_item.url.split('/').2.split(':').0 }}"
        login_port: "{{ wso2am_database_item.url.split('/').2.split(':').1 }}"
        login_user: "{{ wso2am_database_item.username }}"
        login_password: "{{ wso2am_database_item.password }}"
        encoding: "{{ wso2am_database_item.encoding | default('latin1') }}"
        state: import
        target: "{{ wso2am_database_item.load_script_path }}"
      loop: "{{ wso2am_mysql_databases }}"
      loop_control:
        loop_var: wso2am_database_item

  tags:
    - role::wso2am
    - role::wso2am::databases
    - role::wso2am::databases::mysql
