---
# Role artifact tasks

- name: Setup wso2am artifact
  include_role:
    name: amtega.artifact
  vars:
    override:
      id: "wso2am_{{ wso2am_profile }}"
      download: "{{ wso2am_install_required | bool }}"
      version: "{{ wso2am_effective_version }}"
      state: "{{ wso2am_artifact_state }}"
      unarchive: yes
      owner: "{{ wso2am_user }}"
      group: "{{ wso2am_group }}"
      mode: u=rwX,g=rwX,o=
      no_log: "{{ wso2am_no_log | bool }}"
    artifact: "{{ wso2am_artifact | combine(override) }}"
  tags:
    - role::wso2am
    - role::wso2am::download
