---
# Deployment config tasks

- block:
    - name: Setup deployment config file
      template:
        src: >-
          {{ (wso2am_profile == "wso2am")
             | ternary("deployment.toml.j2", "deployment.yml.j2") }}
        dest: "{{ wso2am_deployment_path }}"
        owner: "{{ wso2am_user }}"
        group: "{{ wso2am_group }}"
        mode: 0640
  tags:
    - role::wso2am
    - role::wso2am::config
    - role::wso2am::config::deployment
