---
# Role facts tasks

- block:
    - name: Create local facts directory
      file:
        path: /etc/ansible/facts.d
        mode: 0755
        state: directory

    - name: Setup wso2am local fact
      template:
        src: wso2am.fact.j2
        dest: "{{ wso2am_facts_file_path }}"
        mode: 0640
  tags:
    - role::wso2am::facts
