---
# Role facts tasks

- block:
    - name: Create local facts directory
      file:
        path: /etc/ansible/facts.d
        state: directory

    - name: Setup wso2am local fact
      template:
        src: wso2am.fact.j2
        dest: /etc/ansible/facts.d/wso2am.fact
        mode: 0640
  tags:
    - role::wso2am::facts
