---
# Role install tasks

- block:
    - include_tasks: artifact.yml
      vars:
        wso2am_artifact_state: present

    - name: Setup wso2am base directory
      file:
        path: "{{ wso2am_dir | dirname }}"
        state: directory

    - name: Install wso2am
      copy:
        src: >-
          {{ wso2am_artifact_result.download_path | dirname
             + "/"
             + "wso2am-"
             + (wso2am_profile == "wso2am")
               | ternary("", "analytics-")
             + wso2am_effective_version.split("+") | first
             + "/" }}
        dest: "{{ wso2am_dir }}"
        mode: 0750
        remote_src: yes
      when: wso2am_artifact_result.changed | bool
      vars:
        wso2am_artifact_result: >-
          {{ artifact_result[wso2am_artifact_id] }}

    - name: Setup wso2am directory owner and group
      file:
        path: "{{ wso2am_dir }}"
        owner: "{{ wso2am_user }}"
        recurse: yes
        group: "{{ wso2am_group }}"

    - name: Setup wso2am directory permissions
      shell: >-
        /usr/bin/find {{ wso2am_dir }}
        -type d
        -exec chmod -v 750 \{} \; ;

        /usr/bin/find {{ wso2am_dir }}
        -type f
        -not -regex ".*/bin/.*\.sh$"
        -exec chmod -v 640 \{} \; ;

        /usr/bin/find {{ wso2am_dir }}
        -type f
        -regex ".*/bin/.*\.sh$"
        -exec chmod -v 750 \{} \; ;
      args:
        warn: no
      register: wso2am_setup_permissions
      changed_when: >-
        wso2am_setup_permissions.stdout_lines
        | select("search", "changed from .* to .*")
        | list
        | length > 0
      environment:
        LANGUAGE: en_US

    - include_tasks: artifact.yml
      vars:
        wso2am_artifact_state: absent
  tags:
    - role::wso2am
    - role::wso2am::install
