---

- name: Converge
  hosts: molecule_hosts
  gather_facts: yes
  tasks:
    - name: Setup analytics worker
      include_role:
        name: amtega.wso2am
      vars:
        wso2am_profile: analytics_worker

    - name: Setup analytics dashboard
      include_role:
        name: amtega.wso2am
      vars:
        wso2am_profile: analytics_dashboard
