---
# Deployment config tasks

- block:
    - name: Setup deployment config file
      template:
        src: deployment.toml.j2
        dest: "{{ wso2am_deployment_path }}"
  tags:
    - role::wso2am
    - role::wso2am::config
    - role::wso2am::config::deployment
