---
# Role handlers

- name: Restart wso2am service
  service:
    name: "{{ wso2am_systemd_service_name_map[wso2am_profile] }}"
    state: restarted
    enabled: yes
  listen: restart wso2am
  tags:
    - role::wso2am
    - role::wso2am::restart
