---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Gather service facts
      service_facts:

    - name: Check wso2am service
      assert:
        that: ansible_facts.services["wso2am.service"]["state"] == "running"
