---
# Mysql create tasks

- block:

    - name: Import data to "{{ database.profile }}" mysql database
      mysql_db:
        name: "{{ database.db_name }}"
        login_user: "{{ database.db_username }}"
        login_password: "{{ database.db_password }}"
        state: import
        target: "{{ database.db_load_script_path }}"
  
  tags:
    - role::wso2am
    - role::wso2am::databases
