---
# Oracle config tasks

- block:
    - name: Dowmload jdbc connector
      import_role: amtega_mysql_jdbc_connector
      vars:
        oracle_jdbc_connector_version: "{{ wsoam_database_drivers[oracle].version}}"
        oracle_jdbc_connector_user: "{{ wsoam_database_drivers[oracle].dowmload_user}}"
        oracle_jdbc_connector_password: "{{ wsoam_database_drivers[oracle].dowmload_password}}"

    - name: Copy jdbc jar to wsoam lib directory
      copy:
        src: "{{ oracle_jdbc_connector_ojdbc8_jar_path }}"
        dest: "{{ wso2am_dir }}/repository/components/lib/"
        remote_src: yes

  tags:
    - role::wso2am
    - role::wso2am::databases
