---
# Role service tasks

- block:
    - name: "Setup systemd service file for wso2am {{ wso2am_profile }}"
      template:
        src: "systemd_{{ wso2am_profile }}.j2"
        dest: >-
          {{ wso2am_systemd_service_dir }}/wso2am_{{ wso2am_profile }}.service

    - name: "Setup wso2am {{ wso2am_profile }} service"
      service:
        name: wso2am_{{ wso2am_profile }}
        enabled: yes
        state: started
  tags:
    - role::wso2am
    - role::wso2am::service
